DECLARE @StartAssetId INT = 100003;
DECLARE @MaxLevels INT = 2;
DECLARE @AsOfDate DATETIME = GETUTCDATE();

IF OBJECT_ID('tempdb..#Visited') IS NOT NULL DROP TABLE #Visited;
IF OBJECT_ID('tempdb..#Frontier') IS NOT NULL DROP TABLE #Frontier;
IF OBJECT_ID('tempdb..#Next') IS NOT NULL DROP TABLE #Next;

CREATE TABLE #Visited (
    ASSET_ID INT PRIMARY KEY,
    Level INT NOT NULL
);

CREATE TABLE #Frontier (
    ASSET_ID INT PRIMARY KEY
);

CREATE TABLE #Next (
    ASSET_ID INT PRIMARY KEY
);

INSERT INTO #Visited (ASSET_ID, Level) VALUES (@StartAssetId, 0);
INSERT INTO #Frontier (ASSET_ID) VALUES (@StartAssetId);

DECLARE @d INT = 0;
WHILE @d < @MaxLevels
BEGIN
    TRUNCATE TABLE #Next;

    INSERT INTO #Next (ASSET_ID)
    SELECT DISTINCT X.NeighborId
    FROM (
        SELECT L.CHILD_CI_ID AS NeighborId
        FROM [50004].[CONFIGURATION_ITEM_LINK] AS L
        INNER JOIN #Frontier AS F
            ON L.PARENT_CI_ID = F.ASSET_ID
        INNER JOIN [50004].[AM_ASSET] AS PARENT_CI
            ON PARENT_CI.ASSET_ID = L.PARENT_CI_ID
        INNER JOIN [50004].[AM_ASSET] AS CHILD_CI
            ON CHILD_CI.ASSET_ID = L.CHILD_CI_ID
        WHERE (
            PARENT_CI.REMOVED_DATE IS NULL OR PARENT_CI.REMOVED_DATE > @AsOfDate
            OR CHILD_CI.REMOVED_DATE IS NULL OR CHILD_CI.REMOVED_DATE > @AsOfDate
        )

        UNION ALL

        SELECT L.PARENT_CI_ID AS NeighborId
        FROM [50004].[CONFIGURATION_ITEM_LINK] AS L
        INNER JOIN #Frontier AS F
            ON L.CHILD_CI_ID = F.ASSET_ID
        INNER JOIN [50004].[AM_ASSET] AS PARENT_CI
            ON PARENT_CI.ASSET_ID = L.PARENT_CI_ID
        INNER JOIN [50004].[AM_ASSET] AS CHILD_CI
            ON CHILD_CI.ASSET_ID = L.CHILD_CI_ID
        WHERE (
            PARENT_CI.REMOVED_DATE IS NULL OR PARENT_CI.REMOVED_DATE > @AsOfDate
            OR CHILD_CI.REMOVED_DATE IS NULL OR CHILD_CI.REMOVED_DATE > @AsOfDate
        )
    ) AS X
    WHERE NOT EXISTS (
        SELECT 1
        FROM #Visited AS V
        WHERE V.ASSET_ID = X.NeighborId
    );

    IF NOT EXISTS (SELECT 1 FROM #Next)
    BEGIN
        BREAK;
    END;

    INSERT INTO #Visited (ASSET_ID, Level)
    SELECT N.ASSET_ID, @d + 1
    FROM #Next AS N;

    TRUNCATE TABLE #Frontier;

    INSERT INTO #Frontier (ASSET_ID)
    SELECT N.ASSET_ID
    FROM #Next AS N;

    SET @d = @d + 1;
END;

-- Table 1: nodes (minimal)
SELECT
    V.ASSET_ID,
    A.NETWORK_IDENTIFIER,
    S.CI_STATUS_FR AS CI_STATUS,
    V.Level
FROM #Visited AS V
INNER JOIN [50004].[AM_ASSET] AS A
    ON A.ASSET_ID = V.ASSET_ID
LEFT JOIN [50004].[CMDB_CI_STATUS] AS S
    ON S.CI_STATUS_ID = A.CI_STATUS_ID
ORDER BY V.Level, V.ASSET_ID;

-- Table 2: links (minimal)
SELECT
    L.PARENT_CI_ID,
    L.CHILD_CI_ID,
    R.REFERENCE_FR AS LINK_NAME,
    ISNULL(L.BLOCKING, 0) AS BLOCKING
FROM [50004].[CONFIGURATION_ITEM_LINK] AS L
INNER JOIN #Visited AS VP
    ON VP.ASSET_ID = L.PARENT_CI_ID
INNER JOIN #Visited AS VC
    ON VC.ASSET_ID = L.CHILD_CI_ID
INNER JOIN [50004].[AM_ASSET] AS PARENT_CI
    ON PARENT_CI.ASSET_ID = L.PARENT_CI_ID
INNER JOIN [50004].[AM_ASSET] AS CHILD_CI
    ON CHILD_CI.ASSET_ID = L.CHILD_CI_ID
LEFT JOIN [50004].[AM_REFERENCE] AS R
    ON R.REFERENCE_ID = L.RELATION_TYPE_ID
WHERE (
    PARENT_CI.REMOVED_DATE IS NULL OR PARENT_CI.REMOVED_DATE > @AsOfDate
    OR CHILD_CI.REMOVED_DATE IS NULL OR CHILD_CI.REMOVED_DATE > @AsOfDate
)
ORDER BY VP.Level, VC.Level, L.PARENT_CI_ID, L.CHILD_CI_ID;
